# Project 2
## Step 1: Exploring your data.

##### Load your data in using Pandas and start to explore. Save all of your early exploration code here and include in your final submission.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.stats as stats
import datetime


bb = pd.read_csv('/Users/Tamara/DSI-NYC-1/projects/01-projects-weekly/project-02/assets/billboard.csv')
bb

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",Rock,"September 23, 2000","November 18, 2000",78,63,49,...,*,*,*,*,*,*,*,*,*,*
1,2000,Santana,"Maria, Maria","4,18,00 AM",Rock,"February 12, 2000","April 8, 2000",15,8,6,...,*,*,*,*,*,*,*,*,*,*
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",Rock,"October 23, 1999","January 29, 2000",71,48,43,...,*,*,*,*,*,*,*,*,*,*
3,2000,Madonna,Music,"3,45,00 AM",Rock,"August 12, 2000","September 16, 2000",41,23,18,...,*,*,*,*,*,*,*,*,*,*
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",Rock,"August 5, 2000","October 14, 2000",57,47,45,...,*,*,*,*,*,*,*,*,*,*
5,2000,Janet,Doesn't Really Matter,"4,17,00 AM",Rock,"June 17, 2000","August 26, 2000",59,52,43,...,*,*,*,*,*,*,*,*,*,*
6,2000,Destiny's Child,Say My Name,"4,31,00 AM",Rock'n'roll,"December 25, 1999","March 18, 2000",83,83,44,...,*,*,*,*,*,*,*,*,*,*
7,2000,"Iglesias, Enrique",Be With You,"3,36,00 AM",Latin,"April 1, 2000","June 24, 2000",63,45,34,...,*,*,*,*,*,*,*,*,*,*
8,2000,Sisqo,Incomplete,"3,52,00 AM",Rock'n'roll,"June 24, 2000","August 12, 2000",77,66,61,...,*,*,*,*,*,*,*,*,*,*
9,2000,Lonestar,Amazed,"4,25,00 AM",Country,"June 5, 1999","March 4, 2000",81,54,44,...,*,*,*,*,*,*,*,*,*,*
10,2000,N'Sync,It's Gonna Be Me,"3,10,00 AM",Rock'n'roll,"May 6, 2000","July 29, 2000",82,70,51,...,*,*,*,*,*,*,*,*,*,*
11,2000,"Aguilera, Christina",What A Girl Wants,"3,18,00 AM",Rock'n'roll,"November 27, 1999","January 15, 2000",71,51,28,...,*,*,*,*,*,*,*,*,*,*
12,2000,Vertical Horizon,Everything You Want,"4,01,00 AM",Rock'n'roll,"January 22, 2000","July 15, 2000",70,61,53,...,*,*,*,*,*,*,*,*,*,*
13,2000,Creed,With Arms Wide Open,"3,52,00 AM",Rock'n'roll,"May 13, 2000","November 11, 2000",84,78,76,...,*,*,*,*,*,*,*,*,*,*
14,2000,Aaliyah,Try Again,"4,03,00 AM",Rock'n'roll,"March 18, 2000","June 17, 2000",59,53,38,...,*,*,*,*,*,*,*,*,*,*
15,2000,matchbox twenty,Bent,"4,12,00 AM",Rock,"April 29, 2000","July 22, 2000",60,37,29,...,*,*,*,*,*,*,*,*,*,*
16,2000,"Carey, Mariah",Thank God I Found You,"4,14,00 AM",Rock,"December 11, 1999","February 19, 2000",82,68,50,...,*,*,*,*,*,*,*,*,*,*
17,2000,"Hill, Faith",Breathe,"4,04,00 AM",Rap,"November 6, 1999","April 22, 2000",81,68,62,...,*,*,*,*,*,*,*,*,*,*
18,2000,Mya,Case Of The Ex (Whatcha Gonna Do),"3,50,00 AM",Rock'n'roll,"August 19, 2000","December 2, 2000",72,57,52,...,*,*,*,*,*,*,*,*,*,*
19,2000,Dream,He Loves U Not,"3,43,00 AM",Rock,"September 30, 2000","December 30, 2000",99,92,81,...,*,*,*,*,*,*,*,*,*,*
20,2000,"Braxton, Toni",He Wasn't Man Enough,"4,21,00 AM",Rock,"March 18, 2000","May 6, 2000",63,55,48,...,*,*,*,*,*,*,*,*,*,*
21,2000,"Anthony, Marc",You Sang To Me,"3,50,00 AM",Latin,"February 26, 2000","June 3, 2000",77,54,50,...,*,*,*,*,*,*,*,*,*,*
22,2000,98�,Give Me Just One Night (Una Noche),"3,24,00 AM",Rock,"August 19, 2000","September 30, 2000",51,39,34,...,*,*,*,*,*,*,*,*,*,*
23,2000,Destiny's Child,Jumpin' Jumpin',"3,48,00 AM",Rock,"May 13, 2000","August 19, 2000",74,71,65,...,*,*,*,*,*,*,*,*,*,*
24,2000,3 Doors Down,Kryptonite,"3,53,00 AM",Rock,"April 8, 2000","November 11, 2000",81,70,68,...,*,*,*,*,*,*,*,*,*,*
25,2000,Sisqo,Thong Song,"4,05,00 AM",Rock'n'roll,"January 29, 2000","May 20, 2000",74,63,35,...,*,*,*,*,*,*,*,*,*,*
26,2000,"Aguilera, Christina",I Turn To You,"4,00,00 AM",Rock'n'roll,"April 15, 2000","July 1, 2000",50,39,30,...,*,*,*,*,*,*,*,*,*,*
27,2000,"Houston, Whitney",My Love Is Your Love,"4,16,00 AM",Rock'n'roll,"September 4, 1999","January 8, 2000",81,68,44,...,*,*,*,*,*,*,*,*,*,*
28,2000,Joe,I Wanna Know,"4,57,00 AM",Rock'n'roll,"January 1, 2000","July 1, 2000",94,86,69,...,*,*,*,*,*,*,*,*,*,*
29,2000,"Jordan, Montell",Get It On.. Tonite,"4,34,00 AM",Rap,"October 23, 1999","February 12, 2000",92,80,72,...,*,*,*,*,*,*,*,*,*,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,"3,15,00 AM",R & B,"September 2, 2000","September 9, 2000",91,87,92,...,*,*,*,*,*,*,*,*,*,*
288,2000,Madison Avenue,Don't Call Me Baby,"3,44,00 AM",Electronica,"July 8, 2000","September 16, 2000",98,96,93,...,*,*,*,*,*,*,*,*,*,*
289,2000,Eve,Got It All,"3,48,00 AM",Rap,"July 15, 2000","July 22, 2000",89,88,88,...,*,*,*,*,*,*,*,*,*,*
290,2000,Limp Bizkit,Re-Arranged,"4,08,00 AM",Rock,"December 4, 1999","February 5, 2000",91,91,90,...,*,*,*,*,*,*,*,*,*,*
291,2000,"Spencer, Tracie",Still In My Heart,"4,11,00 AM",Rock,"March 4, 2000","March 11, 2000",95,88,98,...,*,*,*,*,*,*,*,*,*,*
292,2000,Nu Flavor,3 Little Words,"3,54,00 AM",R & B,"June 3, 2000","June 17, 2000",97,97,89,...,*,*,*,*,*,*,*,*,*,*
293,2000,Tamar,If You Don't Wanna Love Me,"4,02,00 AM",Rock,"March 25, 2000","April 15, 2000",98,98,92,...,*,*,*,*,*,*,*,*,*,*
294,2000,"Levert, Gerald",Baby U Are,"4,10,00 AM",R & B,"August 19, 2000","August 26, 2000",96,89,92,...,*,*,*,*,*,*,*,*,*,*
295,2000,"Hart, Beth",L.A. Song,"3,47,00 AM",Country,"November 27, 1999","January 15, 2000",99,100,98,...,*,*,*,*,*,*,*,*,*,*
296,2000,"Diffie, Joe",The Quittin' Kind,"3,23,00 AM",Country,"January 1, 2000","January 22, 2000",98,100,100,...,*,*,*,*,*,*,*,*,*,*
297,2000,Funkmaster Flex,Do You,"4,14,00 AM",Rap,"November 11, 2000","December 2, 2000",92,92,95,...,*,*,*,*,*,*,*,*,*,*
298,2000,"Price, Kelly",Love Sets You Free,"3,46,00 AM",Rock,"May 13, 2000","May 20, 2000",92,91,98,...,*,*,*,*,*,*,*,*,*,*
299,2000,En Vogue,Riddle,"5,10,00 AM",Rock,"June 17, 2000","June 17, 2000",92,92,97,...,*,*,*,*,*,*,*,*,*,*
300,2000,"Herndon, Ty",No Mercy,"4,43,00 AM",Country,"March 18, 2000","May 6, 2000",100,99,99,...,*,*,*,*,*,*,*,*,*,*
301,2000,Anastacia,I'm Outta Love,"4,01,00 AM",Pop,"April 1, 2000","April 1, 2000",92,*,*,...,*,*,*,*,*,*,*,*,*,*
302,2000,Trina,Pull Over,"2,58,00 AM",Rap,"September 9, 2000","September 16, 2000",97,93,96,...,*,*,*,*,*,*,*,*,*,*
303,2000,Lil' Mo,Ta Da,"4,17,00 AM",Rap,"August 12, 2000","September 16, 2000",100,99,97,...,*,*,*,*,*,*,*,*,*,*
304,2000,A*Teens,Dancing Queen,"3,44,00 AM",Pop,"July 8, 2000","July 29, 2000",97,97,96,...,*,*,*,*,*,*,*,*,*,*
305,2000,"Sheist, Shade",Where I Wanna Be,"4,16,00 AM",Rap,"November 11, 2000","November 18, 2000",96,95,99,...,*,*,*,*,*,*,*,*,*,*
306,2000,De La Soul,All Good?,"5,02,00 AM",Rap,"December 23, 2000","December 23, 2000",96,96,100,...,*,*,*,*,*,*,*,*,*,*
307,2000,"Larrieux, Amel",Get Up,"4,02,00 AM",R & B,"March 4, 2000","March 11, 2000",100,97,97,...,*,*,*,*,*,*,*,*,*,*
308,2000,"Braxton, Toni",Spanish Guitar,"4,24,00 AM",Rock,"December 2, 2000","December 2, 2000",98,98,98,...,*,*,*,*,*,*,*,*,*,*
309,2000,Tuesday,I Know,"4,06,00 AM",Rock,"December 30, 2000","December 30, 2000",98,98,*,...,*,*,*,*,*,*,*,*,*,*
310,2000,LL Cool J,Imagine That,"4,00,00 AM",Rap,"August 12, 2000","August 19, 2000",99,98,*,...,*,*,*,*,*,*,*,*,*,*
311,2000,Master P,Souljas,"3,33,00 AM",Rap,"November 18, 2000","November 18, 2000",98,*,*,...,*,*,*,*,*,*,*,*,*,*
312,2000,Ghostface Killah,Cherchez LaGhost,"3,04,00 AM",R & B,"August 5, 2000","August 5, 2000",98,*,*,...,*,*,*,*,*,*,*,*,*,*
313,2000,"Smith, Will",Freakin' It,"3,58,00 AM",Rap,"February 12, 2000","February 12, 2000",99,99,99,...,*,*,*,*,*,*,*,*,*,*
314,2000,Zombie Nation,Kernkraft 400,"3,30,00 AM",Rock,"September 2, 2000","September 2, 2000",99,99,*,...,*,*,*,*,*,*,*,*,*,*
315,2000,"Eastsidaz, The",Got Beef,"3,58,00 AM",Rap,"July 1, 2000","July 1, 2000",99,99,*,...,*,*,*,*,*,*,*,*,*,*
316,2000,Fragma,Toca's Miracle,"3,22,00 AM",R & B,"October 28, 2000","October 28, 2000",99,*,*,...,*,*,*,*,*,*,*,*,*,*

##### Write a brief description of your data, and any interesting observations you've made thus far.

The data above is a collection of songs released in 2000 which have managed to chart on the Billboard. A lot of the data is missing on the table and are in * to show that there is no value. The time is arranged in a weird fashion as it is impossible to know if the time is actually telling the time or if it's the actual length of the song. The fact that AM is added makes it more confusing. The genres are also mislabeled or not as labeling a genre a certain way is up to the person and maybe the billboards have their own way of classifying songs and also the genres were (I think) according to the song and not to the type of singer the artist is. I decided The dates are also printed incorrectly and are not in the day-month-year order.

## Step 2: Clean your data.

##### Do some rudimentary cleaning. Rename any columns that are poorly named, shorten any strings that may be too long, fill in any missing values. Explain your rationale for the way you choose to "impute" the missing data.

In [2]:
bb.columns.values

array(['year', 'artist.inverted', 'track', 'time', 'genre', 'date.entered',
       'date.peaked', 'x1st.week', 'x2nd.week', 'x3rd.week', 'x4th.week',
       'x5th.week', 'x6th.week', 'x7th.week', 'x8th.week', 'x9th.week',
       'x10th.week', 'x11th.week', 'x12th.week', 'x13th.week',
       'x14th.week', 'x15th.week', 'x16th.week', 'x17th.week',
       'x18th.week', 'x19th.week', 'x20th.week', 'x21st.week',
       'x22nd.week', 'x23rd.week', 'x24th.week', 'x25th.week',
       'x26th.week', 'x27th.week', 'x28th.week', 'x29th.week',
       'x30th.week', 'x31st.week', 'x32nd.week', 'x33rd.week',
       'x34th.week', 'x35th.week', 'x36th.week', 'x37th.week',
       'x38th.week', 'x39th.week', 'x40th.week', 'x41st.week',
       'x42nd.week', 'x43rd.week', 'x44th.week', 'x45th.week',
       'x46th.week', 'x47th.week', 'x48th.week', 'x49th.week',
       'x50th.week', 'x51st.week', 'x52nd.week', 'x53rd.week',
       'x54th.week', 'x55th.week', 'x56th.week', 'x57th.week',
       'x58th.week', 'x59th.week', 'x60th.week', 'x61st.week',
       'x62nd.week', 'x63rd.week', 'x64th.week', 'x65th.week',
       'x66th.week', 'x67th.week', 'x68th.week', 'x69th.week',
       'x70th.week', 'x71st.week', 'x72nd.week', 'x73rd.week',
       'x74th.week', 'x75th.week', 'x76th.week'], dtype=object)

In [3]:
bb.replace('*', np.nan, inplace=True)
bb.head(5)

# I chose to put a NaN in place of the *'s because there was a lot of missing data especially for the weeks beyond 
# week 3 that I did not think were needed as there was sufficient data available.

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",Rock,"September 23, 2000","November 18, 2000",78,63,49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria","4,18,00 AM",Rock,"February 12, 2000","April 8, 2000",15,8,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",Rock,"October 23, 1999","January 29, 2000",71,48,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,"3,45,00 AM",Rock,"August 12, 2000","September 16, 2000",41,23,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",Rock,"August 5, 2000","October 14, 2000",57,47,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
new_cols = ['Year', 'Artist', 'Track', 'Time', 'Genre', 'Date_Entered', 'Date_Peaked', '1st_week', '2nd_week', '3rd_week', '4th week', 'x5th.week', 'x6th.week', 'x7th.week', 'x8th.week', 'x9th.week', 'x10th.week', 'x11th.week', 'x12th.week', 'x13th.week', 'x14th.week', 'x15th.week', 'x16th.week', 'x17th.week', 'x18th.week', 'x19th.week', 'x20th.week', 'x21st.week', 'x22nd.week', 'x23rd.week', 'x24th.week', 'x25th.week', 'x26th.week', 'x27th.week', 'x28th.week', 'x29th.week', 'x30th.week', 'x31st.week', 'x32nd.week', 'x33rd.week', 'x34th.week', 'x35th.week', 'x36th.week', 'x37th.week', 'x38th.week', 'x39th.week', 'x40th.week', 'x41st.week', 'x42nd.week', 'x43rd.week', 'x44th.week', 'x45th.week', 'x46th.week', 'x47th.week', 'x48th.week', 'x49th.week', 'x50th.week', 'x51st.week', 'x52nd.week', 'x53rd.week', 'x54th.week', 'x55th.week', 'x56th.week', 'x57th.week', 'x58th.week', 'x59th.week', 'x60th.week', 'x61st.week', 'x62nd.week', 'x63rd.week', 'x64th.week', 'x65th.week', 'x66th.week', 'x67th.week', 'x68th.week', 'x69th.week', 'x70th.week', 'x71st.week', 'x72nd.week', 'x73rd.week', 'x74th.week', 'x75th.week', 'x76th.week']
bb.columns = new_cols

In [5]:
bb.head(5)

,Year,Artist,Track,Time,Genre,Date_Entered,Date_Peaked,1st_week,2nd_week,3rd_week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",Rock,"September 23, 2000","November 18, 2000",78,63,49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria","4,18,00 AM",Rock,"February 12, 2000","April 8, 2000",15,8,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",Rock,"October 23, 1999","January 29, 2000",71,48,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,"3,45,00 AM",Rock,"August 12, 2000","September 16, 2000",41,23,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",Rock,"August 5, 2000","October 14, 2000",57,47,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:

bb.tail(5)

,Year,Artist,Track,Time,Genre,Date_Entered,Date_Peaked,1st_week,2nd_week,3rd_week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
312,2000,Ghostface Killah,Cherchez LaGhost,"3,04,00 AM",R & B,"August 5, 2000","August 5, 2000",98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,"3,58,00 AM",Rap,"February 12, 2000","February 12, 2000",99,99,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,"3,30,00 AM",Rock,"September 2, 2000","September 2, 2000",99,99,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,"3,58,00 AM",Rap,"July 1, 2000","July 1, 2000",99,99,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,"3,22,00 AM",R & B,"October 28, 2000","October 28, 2000",99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
a = []
for date in bb['Date_Entered']:
    x = pd.to_datetime(date)
    a.append(x)

b=[]
for date in bb['Date_Peaked']:
    y=pd.to_datetime(date)
    b.append(y)

bb['Date_Entered'] = a 
bb['Date_Peaked'] = b

In [8]:
new_time=[]
for item in bb['Time']:
    x = item.split(',')
    item = int(x[0])*60 + int(x[1])
    new_time.append(item)
bb['Time'] = new_time

# I couldnt get the time to print correctly. I tried many different ways to get it to print in the hr:min:sec format 
# for hours and I couldnt find a solution.

##### Using Pandas' built in `melt` function, pivot the weekly ranking data to be long rather than wide. As a result, you will have removed the 72 'week' columns and replace it with two: Week and Ranking. There will now be multiple entries for each song, one for each week on the Billboard rankings.

In [9]:
bb_melted = pd.melt(bb, id_vars = ['Year', 'Artist','Track','Genre', 'Date_Entered', 'Date_Peaked'], var_name='Week', value_name = 'Ranking')

In [10]:
null_values = bb_melted['Ranking'].isnull()
null_values.value_counts()

True     18785
False     5624
Name: Ranking, dtype: int64

In [11]:
bb_clean = bb_melted.dropna(axis = 0)

In [12]:
top_track= bb_clean[bb_clean['Ranking']==1]
top_track_pivot = pd.pivot_table(top_track, index = 'Artist', values='Ranking', aggfunc=np.sum)

In [13]:
avg_rank_genre = pd.pivot_table(bb_melted, index=['Genre'], values= 'Ranking')
avg_rank_genre

DataError: No numeric types to aggregate

## Step 3: Visualize your data.

##### Using a plotting utility of your choice (Tableau or python modules or both), create visualizations that will provide context to your data. There is no minimum or maximum number of graphs you should generate, but there should be a clear and consistent story being told. Give insights to the distribution, statistics, and relationships of the data.

## Step 4: Create a Problem Statement.

##### Having explored the data, come up with a problem statement for this data set. You can feel free to introduce data from any other source to support your problem statement, just be sure to provide a link to the origin of the data. Once again- be creative!

## Step 5: Brainstorm your Approach.
##### In bullet-list form, provide a proposed approach for evaluating your problem statement. This can be somewhat high-level, but start to think about ways you can massage the data for maximum efficacy.

## Step 6: Create a blog post with your code snippets and visualizations.
##### Data Science is a growing field, and the Tech industry thrives off of collaboration and sharing of knowledge. Blogging is a powerful means for pushing the needle forward in our field. Using your blogging platform of choice, create a post describing each of the 5 steps above. Rather than writing a procedural text, imagine you're describing the data, visualizations, and conclusions you've arrived at to your peers. Aim for a minimum of 500 words.

## BONUS: The Content Managers working for the Podcast Publishing Company have recognized you as a thought leader in your field. They've asked you to pen a white paper (minimum 500 words) on the subject of 'What It Means To Have Clean Data'. This will be an opinion piece read by a wide audience, so be sure to back up your statements with real world examples or scenarios.

##### Hint: To get started, look around on the internet for articles, blog posts, papers, youtube videos, podcasts, reddit discussions, anything that will help you understand the challenges and implications of dealing with big data. This should be a personal reflection on everything you've learned this week, and the learning goals that have been set out for you going forward.